name: gsplat_2dgs
background_color: null
make_scale_invariant: false
radius_clip: 0.0
eps2d: 0.3
sh_degree: 3
packed: true
tile_size: 16
render_mode: RGB
sparse_grad: false
absgrad: false
distloss: false
